const data = [
  {title:"NicoleMatt",    classes:["prob","roof", "tatted" ]},
  {title:"Elena",         classes:["prob","roof", "frenemy", "newfriend"]},
  {title:"Mel",           classes:["prob","roof", "frenemy", "newfriend"]},
  {title:"GrantPong",     classes:["prob","roof", "music"]},
  {title:"CheyAmsterdam", classes:["overseas", "sunny"]},
  {title:"TheoDad",   classes:["hug"]},
  {title:"EmerBackyard",   classes:[]},
  {title:"FrankieIsland",   classes:["frankie"]},
  {title:"FrankieSquiz",   classes:["frankie", "hug"]},
  {title:"GrantStizzy",   classes:[]},
  {title:"KatCouch",   classes:["couch"]},
  {title:"MaxCouch",   classes:["couch"]},
  {title:"MaxDad",   classes:["hug"]},
  {title:"MeHighHat",   classes:["hat"]},
  {title:"MeSquiz",   classes:["hug", "blonde", "tatted", "hat"]},
  {title:"NicoleHat",   classes:["hat"]},
  {title:"NicoleHighHat",   classes:["hat"]},
  {title:"RachelHat",   classes:["hat"]},
  {title:"RachelHighHat",   classes:["hat"]},
  {title:"TheoBirthday",   classes:["birthday"]},
  {title:"AndyPorch",     classes:[]},
  {title:"AndyPuzzle",    classes:[]},
  {title:"CheyBed",       classes:["overseas"]},
  {title:"GrantLATrio",   classes:["hat"]},
  {title:"JayaHug",       classes:["hug"]},
  {title:"KatieApartment",classes:["prob"]},
  {title:"KaysonPong",    classes:["roof", "prob"]},
  {title:"Lina",          classes:["overseas"]},
  {title:"LyronLATrio",   classes:["roof", "lyron"]},
  {title:"MeBeach",       classes:["hat", "blonde"]},
  {title:"RachelBeach",   classes:["hat"]},
  {title:"NicoleCouch",   classes:["tatted", "couch"]},
  {title:"RachelCouch",   classes:["couch"]},
  {title:"SarahPuzzle",   classes:["tatted"]},
  {title:"AndyFries",     classes:["hat", "eating"]},
  {title:"JayaCheersSelfie", classes:["prob"]},
  {title:"MariaTajin",   classes:[""]},
  {title:"MeMatt",        classes:["def", "hat", "blonde", "tatted"]},
  {title:"MeTajin",       classes:["tatted", "tongue"]},
  {title:"TrishTajin",    classes:["frenemy"]},
  {title:"AkheelChairGroup",   classes:["prob", "night"]},
  {title:"EmilyChairGroup",   classes:["frenemy", "night"]},
  {title:"FrankieCheers",   classes:["frankie", "night"]},
  {title:"FrankieRock",   classes:["frankie", "def"]},
  {title:"GaryVR",        classes:["music"]},
  {title:"JuliaWortman",  classes:["frenemy", "night"]},
  {title:"MariaWineSip",  classes:["night", "prob"]},
  {title:"MeMenSarah",    classes:["night"]},
  {title:"CalvinChairGroup",   classes:["night"]},
  {title:"MariaChairGroup",   classes:["night"]},
  {title:"MeBirthday",    classes:["def", "birthday", "tatted"]},
  {title:"MeChairGroup",  classes:["night", "prob"]},
  {title:"AvaBiden",      classes:["frenemy", "election"]},
  {title:"EmilyEmilySelfie",   classes:["frenemy", "tongue", "night"]},
  {title:"FrankieTableGroup",   classes:["frankie", "night"]},
  {title:"GaryBiden",     classes:["election"]},
  {title:"GaryTableGroup",   classes:["night"]},
  {title:"GaryTargetMask",   classes:["mask"]},
  {title:"LyronSheesh",   classes:["joshua", "sunny", "lyron"]},
  {title:"MariaBiden",    classes:["election"]},
  {title:"MariaEmilySelfie",   classes:["night"]},
  {title:"MeEmilySelfie",   classes:["night"]},
  {title:"MeTableGroup",   classes:[]},
  {title:"KaysonBleach",   classes:["prob"]},
  {title:"CheyJTTrio",   classes:["joshua", "newfriend"]},
  {title:"FrankieJTTrio",   classes:["joshua", "frankie"]},
  {title:"KaysonJTTrio",   classes:["joshua"]},
  {title:"KatPinkDuo1",   classes:["tongue"]},
  {title:"MePinkDuo1",   classes:["tongue", "tatted", "pink"]},
  {title:"GrantTableMax",   classes:["joshua"]},
  {title:"KaysonRockGroup",   classes:["joshua"]},
  {title:"LyronRockGroup",   classes:["joshua", "lyron"]},
  {title:"MattWatermelon",   classes:["joshua", "eating", "sunny"]},
  {title:"MaxRockGroup",   classes:["joshua"]},
  {title:"MeRockGroup",   classes:["joshua", "tatted", "blonde"]},
  {title:"NicoleRockGroup",   classes:["joshua"]},
  {title:"RachelRockGroup",   classes:["joshua"]},
  {title:"RachelWatermelon",   classes:["joshua", "eating", "sunny"]},
  {title:"FrankieRockGroup",   classes:["joshua", "frankie"]},
  {title:"GrantFireGroup",   classes:["joshua"]},
  {title:"IndyFireGroup",   classes:["joshua"]},
  {title:"MaxFireGroup",   classes:["joshua"]},
  {title:"SarahRockGroup",   classes:["joshua"]},
  {title:"GrantBowl",   classes:["eating"]},
  {title:"GrantTwerk",   classes:["music", "twerk"]},
  {title:"JayaTan",   classes:["sunny"]},
  {title:"KatPink",   classes:[]},
  {title:"LyronJTCutoff",   classes:["joshua", "lyron"]},
  {title:"MeGlenrock",   classes:[]},
  {title:"MePink",   classes:["tatted", "pink"]},
  {title:"RachelJTCutoff",   classes:["joshua"]},
  {title:"SarahGlenrock",   classes:[]},
  {title:"SarahJTCutoff",   classes:["joshua"]},
  {title:"EishJT5",   classes:["joshua"]},
  {title:"FrankieSquint",   classes:["joshua", "frankie", "blonde", "sunny"]},
  {title:"LyronFrat",   classes:["music", "lyron"]},
  {title:"LyronInkbox",   classes:["joshua", "sunny", "lyron"]},
  {title:"MattFratt",   classes:["music"]},
  {title:"MattInkbox",   classes:["joshua", "sunny"]},
  {title:"MaxJT5",   classes:["joshua"]},
  {title:"MeJT5",   classes:["joshua"]},
  {title:"MeSquint",   classes:["joshua", "tatted", "blonde", "sunny"]},
  {title:"NicoleJT5",   classes:["joshua"]},
  {title:"RachelJT5",   classes:["joshua"]},
  {title:"SarahJT5",   classes:["joshua"]},
  {title:"IzzySqueeze",   classes:["tatted", "prob"]},
  {title:"MeRoofCheese",   classes:["roof", "def", "tatted", "blonde"]},
  {title:"MeSqueeze",   classes:["tatted", "prob"]},
  {title:"NicoleRoofCheese",   classes:["roof", "prob", "tatted"]},
  {title:"SarahFloor",   classes:["lay"]},
  {title:"SebaCouch",   classes:["couch"]},
  {title:"IzzyCloseS",   classes:["tatted", "prob"]},
  {title:"IzzyCounter",   classes:["tatted"]},
  {title:"IzzyTrioSqueeze",   classes:["tatted", "def"]},
  {title:"LeroyCoffee",   classes:["mask"]},
  {title:"MeCloseSelfie",   classes:["tatted", "prob"]},
  {title:"MeCoffee",   classes:["tatted", "mask"]},
  {title:"MeCouch",   classes:["tatted", "couch"]},
  {title:"MeCounter",   classes:["tatted"]},
  {title:"MeTrioSqueeze",   classes:["tatted", "def"]},
  {title:"SarahCloseS",   classes:["prob"]},
  {title:"SarahCouch",   classes:["couch"]},
  {title:"SarahLimes",   classes:["prob"]},
  {title:"SebaCar",   classes:[]},
  {title:"SebaCoffee",   classes:["mask"]},
  {title:"SebaCounter",   classes:[]},
  {title:"MeSebaSelfie",   classes:["tatted", "prob"]},
  {title:"SarahAyy",   classes:["prob"]},
  {title:"SarahBookstore",   classes:["mask"]},
  {title:"SarahTrioSqueeze",   classes:["def"]},
  {title:"SebaBookstore",   classes:["mask"]},
  {title:"CalvinClassic",   classes:[]},
  {title:"EmilyChip",   classes:["prob", "frenemy"]},
  {title:"EmilyClassic",   classes:["frenemy"]},
  {title:"KatieBoyband",   classes:["newfriend"]},
  {title:"MariaHalloween",   classes:["def"]},
  {title:"MeCrevice",   classes:["joshua"]},
  {title:"MeHalloween",   classes:["def"]},
  {title:"SarahBoyband",   classes:[]},
  {title:"SarahCrevice",   classes:["joshua"]},
  {title:"TrishClassic",   classes:["frenemy"]},
  {title:"TrishHalloween",   classes:["def", "frenemy"]},
  {title:"TrishTC",   classes:["def", "frenemy", "tongue"]},
  {title:"AndyGRQuad",   classes:["newfriend"]},
  {title:"AndyCouch",   classes:["newfriend", "couch"]},
  {title:"JasonGRQuad",   classes:["newfriend"]},
  {title:"JasonHOCO",   classes:["newfriend"]},
  {title:"JayaMax",   classes:["hug"]},
  {title:"JayaMe",   classes:["hug"]},
  {title:"KatieGRQuad",   classes:["newfriend"]},
  {title:"MaxJaya",   classes:["hug"]},
  {title:"MeGrantNicole",   classes:["hug", "blonde", "tatted"]},
  {title:"MeJaya",   classes:["hug"]},
  {title:"MeStoner",   classes:["sunny", "mask"]},
  {title:"MeTitanic",   classes:["hug", "blonde"]},
  {title:"NicoleGrantMe",   classes:["hug"]},
  {title:"SarahGRQuad",   classes:[]},
  {title:"SarahHOCO",   classes:[]},
  {title:"SarahTitanic",   classes:["hug"]},
  {title:"KatBalloons",   classes:["birthday"]},
  {title:"KatBalloons2",   classes:["birthday"]},
  {title:"LyronBalloons",   classes:["lyron"]},
  {title:"LyronPan",   classes:["lyron"]},
  {title:"MattLaptop",   classes:[]},
  {title:"MaxStool",   classes:[]},
  {title:"RachelLaptop",   classes:[]},
  {title:"SarahTheoFloor",   classes:["hug"]},
  {title:"TheoSarahFloor",   classes:["hug"]},
  {title:"BritPaso5",   classes:["newfriend", "prob", "tongue"]},
  {title:"BritTwerk",   classes:["twerk", "newfriend"]},
  {title:"CalvinPaso5",   classes:[]},
  {title:"EmerDye",   classes:["pink"]},
  {title:"EmerMirror",   classes:["pink"]},
  {title:"LyronPaso5",   classes:["lyron"]},
  {title:"LyronPasoS",   classes:["lyron"]},
  {title:"LyronSwag",   classes:["lyron"]},
  {title:"MeTrio1",   classes:["tatted"]},
  {title:"SarahPaso5",   classes:[]},
  {title:"TheoMirror",   classes:[]},
  {title:"BritEmer",   classes:["newfriend"]},
  {title:"EmerBrit",   classes:["newfriend"]},
  {title:"EmerTrio1",   classes:["newfriend"]},
  {title:"EmerTrio2",   classes:["newfriend"]},
  {title:"GrantPasoPong",   classes:["prob"]},
  {title:"LyronPasoPong",   classes:["lyron", "prob"]},
  {title:"LyronShaka",   classes:["lyron"]},
  {title:"MattPasoPong",   classes:["prob"]},
  {title:"MeTrio2",   classes:["tatted"]},
  {title:"NicoleSD",   classes:[]},
  {title:"RachelPasoPong",   classes:["prob"]},
  {title:"TheoArmrest",   classes:[]},
  {title:"JayaBed",   classes:[]},
  {title:"JayaKat",   classes:["hug"]},
  {title:"JayaStairs",   classes:["hug"]},
  {title:"KatJaya",   classes:["hug"]},
  {title:"LyronTitanic",   classes:["lyron", "hug"]},
  {title:"KatyaBridge",   classes:["sunny"]},
  {title:"MariaClassic",   classes:[]},
  {title:"MariaOverE",   classes:["prob"]},
  {title:"MeOverE",   classes:["prob"]},
  {title:"TrishChip",   classes:["frenemy"]},
  {title:"AndyBoyband",   classes:["newfriend"]},
  {title:"AvaIce",   classes:["frenemy"]},
  {title:"EmilyHalloween",   classes:["mask", "def", "frenemy"]},
  {title:"EmilyTC",   classes:["frenemy"]},
  {title:"FrankueClassic",   classes:["frankie"]},
  {title:"MaxHighlight",   classes:[]},
  {title:"MaxStairs",   classes:["hug"]},
  {title:"TheoHighlight",   classes:[]},
  {title:"TheoTitanic",   classes:["hug"]},
]
